#!/usr/bin/env ruby
require 'fileutils'
require 'pathname'

# Get into script directory
Dir.chdir(File.dirname(__FILE__))
pwd = Dir.pwd

# Set the shell
zsh = `cat /etc/shells | grep /zsh | tail -n 1`.strip
`chsh -s #{zsh}` if `grep "^$USER:" /etc/passwd | cut -d : -f 7`.strip != zsh

# Compile custom terminfo
`tic xterm-screen-256color.terminfo`

# Create symlinks
linkables = Dir.glob('*/**{.symlink}')

skip_all = false
overwrite_all = false
backup_all = false

linkables.each do |linkable|
	overwrite = false
	backup = false

	file = linkable.split('/').last.split('.symlink').last.gsub(/__/,'/')
	target = "#{ENV["HOME"]}/.#{file}"
	linkable = Pathname.new(pwd+'/'+linkable).realpath.to_s

	if File.exists?(target) || File.symlink?(target)
		next if File.symlink?(target) and File.readlink(target)==linkable
		unless skip_all || overwrite_all || backup_all
			puts "File already exists: #{target}, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all"
			case STDIN.gets.chomp
			when 'o' then overwrite = true
			when 'b' then backup = true
			when 'O' then overwrite_all = true
			when 'B' then backup_all = true
			when 'S' then skip_all = true
			when 's' then next
			end
		end
		FileUtils.rm_rf(target) if overwrite || overwrite_all
		`mv "$HOME/.#{file}" "$HOME/.#{file}.backup"` if backup || backup_all
	else
		FileUtils.mkdir_p(File.dirname(target))
	end
	
	`ln -s "#{linkable}" "#{target}"`
end
